// Command generate-capabilities generates schema-derived types for the
// introspection client by reading the GraphQL schema and the mutations
// directory structure.
//
// It emits a single Go file containing SchemaCapabilities, the introspection
// query string, the response structs, and parseCapabilities — everything that
// must stay in sync with the schema. The HTTP logic in introspect.go is left
// untouched.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"log"
	"os"
	"sort"

	"github.com/vektah/gqlparser/v2"
	"github.com/vektah/gqlparser/v2/ast"
)

type mutationField struct {
	TypeName string // Return type in schema, e.g. "DockerMutations", "VmMutations"
	Alias    string // Introspection query alias, e.g. "dockerMutations", "vmMutations"
}

func main() {
	var (
		schemaPath   string
		mutationsDir string
		outFile      string
	)

	flag.StringVar(&schemaPath, "schema", "", "path to schema.graphql")
	flag.StringVar(&mutationsDir, "mutations", "", "path to mutations directory")
	flag.StringVar(&outFile, "out", "", "output file path")
	flag.Parse()

	if schemaPath == "" || mutationsDir == "" || outFile == "" {
		log.Fatal("usage: generate-capabilities -schema <path> -mutations <dir> -out <file>")
	}

	mutations := resolveMutations(schemaPath, mutationsDir)

	var buf bytes.Buffer
	generate(&buf, mutations)

	src, err := format.Source(buf.Bytes())
	if err != nil {
		log.Fatalf("failed to format generated code: %v\n--- source ---\n%s", err, buf.String())
	}

	if err := os.WriteFile(outFile, src, 0o644); err != nil {
		log.Fatalf("failed to write %s: %v", outFile, err)
	}
}

// resolveMutations finds each subdirectory of mutationsDir, looks up the
// corresponding field in the Mutation type, and returns the ordered list.
func resolveMutations(schemaPath, mutationsDir string) []mutationField {
	src, err := os.ReadFile(schemaPath)
	if err != nil {
		log.Fatalf("failed to read schema %s: %v", schemaPath, err)
	}

	schema, gqlErr := gqlparser.LoadSchema(&ast.Source{Name: schemaPath, Input: string(src)})
	if gqlErr != nil {
		log.Fatalf("failed to parse schema: %v", gqlErr)
	}

	mutationType := schema.Types["Mutation"]
	if mutationType == nil {
		log.Fatal("Mutation type not found in schema")
	}

	entries, err := os.ReadDir(mutationsDir)
	if err != nil {
		log.Fatalf("failed to read mutations dir %s: %v", mutationsDir, err)
	}

	var mutations []mutationField
	for _, e := range entries {
		if !e.IsDir() {
			continue
		}
		fieldName := e.Name()
		field := mutationType.Fields.ForName(fieldName)
		if field == nil {
			log.Fatalf("mutations subdir %q has no corresponding field in Mutation type", fieldName)
		}
		mutations = append(mutations, mutationField{
			TypeName: field.Type.Name(),
			Alias:    fieldName + "Mutations",
		})
	}

	sort.Slice(mutations, func(i, j int) bool {
		return mutations[i].Alias < mutations[j].Alias
	})

	return mutations
}

func generate(w *bytes.Buffer, mutations []mutationField) {
	fmt.Fprint(w, "// Code generated by \"go run ./cmd/generate-capabilities\". DO NOT EDIT.\npackage client\n\n")
	writeSchemaCapabilities(w, mutations)
	writeIntrospectionQuery(w, mutations)
	writeIntrospectTypes(w, mutations)
	writeParseCapabilities(w, mutations)
}

func writeSchemaCapabilities(w *bytes.Buffer, mutations []mutationField) {
	fmt.Fprint(w, "// SchemaCapabilities holds GraphQL fields detected via introspection.\n")
	fmt.Fprint(w, "// A nil map means the type was not found in the server's schema.\n")
	fmt.Fprint(w, "type SchemaCapabilities struct {\n")
	fmt.Fprint(w, "\t// QueryFields maps top-level Query field names that exist on this server.\n")
	fmt.Fprint(w, "\tQueryFields map[string]bool\n")
	for _, m := range mutations {
		fmt.Fprintf(w, "\t// %s maps %s field names. Nil if not supported.\n", m.TypeName, m.TypeName)
		fmt.Fprintf(w, "\t%s map[string]bool\n", m.TypeName)
	}
	fmt.Fprint(w, "}\n\n")
}

func writeIntrospectionQuery(w *bytes.Buffer, mutations []mutationField) {
	fmt.Fprint(w, "// introspectionQuery fetches the mutation type fields used by this CLI.\n")
	fmt.Fprint(w, "const introspectionQuery = `{\n")
	for _, m := range mutations {
		fmt.Fprintf(w, "  %s: __type(name: \"%s\") { fields { name } }\n", m.Alias, m.TypeName)
	}
	fmt.Fprint(w, "  schema: __schema { queryType { fields { name } } }\n}`\n\n")
}

func writeIntrospectTypes(w *bytes.Buffer, mutations []mutationField) {
	fmt.Fprint(w, "type introspectFieldEntry struct {\n\tName string `json:\"name\"`\n}\n\n")
	fmt.Fprint(w, "type introspectTypeResult struct {\n\tFields []introspectFieldEntry `json:\"fields\"`\n}\n\n")

	fmt.Fprint(w, "type introspectResponse struct {\n\tData struct {\n")
	for _, m := range mutations {
		fmt.Fprintf(w, "\t\t%s *introspectTypeResult `json:\"%s\"`\n", m.TypeName, m.Alias)
	}
	fmt.Fprint(w, "\t\tSchema struct {\n")
	fmt.Fprint(w, "\t\t\tQueryType struct {\n")
	fmt.Fprint(w, "\t\t\t\tFields []introspectFieldEntry `json:\"fields\"`\n")
	fmt.Fprint(w, "\t\t\t} `json:\"queryType\"`\n")
	fmt.Fprint(w, "\t\t} `json:\"schema\"`\n")
	fmt.Fprint(w, "\t} `json:\"data\"`\n")
	fmt.Fprint(w, "\tErrors []struct {\n\t\tMessage string `json:\"message\"`\n\t} `json:\"errors\"`\n}\n\n")
}

func writeParseCapabilities(w *bytes.Buffer, mutations []mutationField) {
	fmt.Fprint(w, "// parseCapabilities converts an introspection response to SchemaCapabilities.\n")
	fmt.Fprint(w, "func parseCapabilities(r introspectResponse) *SchemaCapabilities {\n")
	fmt.Fprint(w, "\treturn &SchemaCapabilities{\n")
	fmt.Fprint(w, "\t\tQueryFields: fieldsToSet(r.Data.Schema.QueryType.Fields),\n")
	for _, m := range mutations {
		fmt.Fprintf(w, "\t\t%s: typeToSet(r.Data.%s),\n", m.TypeName, m.TypeName)
	}
	fmt.Fprint(w, "\t}\n}\n")
}
