[git]
conventional_commits = true
filter_unconventional = true
filter_commits = true
commit_parsers = [
  { message = "^feat", group = "Features" },
  { message = "^fix",  group = "Bug Fixes" },
  { message = "^",     skip = true },
]
