// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

package client

import (
	"context"

	"github.com/Khan/genqlient/graphql"
)

type ArrayDiskStatus string

const (
	ArrayDiskStatusDiskNp        ArrayDiskStatus = "DISK_NP"
	ArrayDiskStatusDiskOk        ArrayDiskStatus = "DISK_OK"
	ArrayDiskStatusDiskNpMissing ArrayDiskStatus = "DISK_NP_MISSING"
	ArrayDiskStatusDiskInvalid   ArrayDiskStatus = "DISK_INVALID"
	ArrayDiskStatusDiskWrong     ArrayDiskStatus = "DISK_WRONG"
	ArrayDiskStatusDiskDsbl      ArrayDiskStatus = "DISK_DSBL"
	ArrayDiskStatusDiskNpDsbl    ArrayDiskStatus = "DISK_NP_DSBL"
	ArrayDiskStatusDiskDsblNew   ArrayDiskStatus = "DISK_DSBL_NEW"
	ArrayDiskStatusDiskNew       ArrayDiskStatus = "DISK_NEW"
)

var AllArrayDiskStatus = []ArrayDiskStatus{
	ArrayDiskStatusDiskNp,
	ArrayDiskStatusDiskOk,
	ArrayDiskStatusDiskNpMissing,
	ArrayDiskStatusDiskInvalid,
	ArrayDiskStatusDiskWrong,
	ArrayDiskStatusDiskDsbl,
	ArrayDiskStatusDiskNpDsbl,
	ArrayDiskStatusDiskDsblNew,
	ArrayDiskStatusDiskNew,
}

type ArrayState string

const (
	ArrayStateStarted             ArrayState = "STARTED"
	ArrayStateStopped             ArrayState = "STOPPED"
	ArrayStateNewArray            ArrayState = "NEW_ARRAY"
	ArrayStateReconDisk           ArrayState = "RECON_DISK"
	ArrayStateDisableDisk         ArrayState = "DISABLE_DISK"
	ArrayStateSwapDsbl            ArrayState = "SWAP_DSBL"
	ArrayStateInvalidExpansion    ArrayState = "INVALID_EXPANSION"
	ArrayStateParityNotBiggest    ArrayState = "PARITY_NOT_BIGGEST"
	ArrayStateTooManyMissingDisks ArrayState = "TOO_MANY_MISSING_DISKS"
	ArrayStateNewDiskTooSmall     ArrayState = "NEW_DISK_TOO_SMALL"
	ArrayStateNoDataDisks         ArrayState = "NO_DATA_DISKS"
)

var AllArrayState = []ArrayState{
	ArrayStateStarted,
	ArrayStateStopped,
	ArrayStateNewArray,
	ArrayStateReconDisk,
	ArrayStateDisableDisk,
	ArrayStateSwapDsbl,
	ArrayStateInvalidExpansion,
	ArrayStateParityNotBiggest,
	ArrayStateTooManyMissingDisks,
	ArrayStateNewDiskTooSmall,
	ArrayStateNoDataDisks,
}

type ArrayStateInputState string

const (
	ArrayStateInputStateStart ArrayStateInputState = "START"
	ArrayStateInputStateStop  ArrayStateInputState = "STOP"
)

var AllArrayStateInputState = []ArrayStateInputState{
	ArrayStateInputStateStart,
	ArrayStateInputStateStop,
}

type ContainerPortType string

const (
	ContainerPortTypeTcp ContainerPortType = "TCP"
	ContainerPortTypeUdp ContainerPortType = "UDP"
)

var AllContainerPortType = []ContainerPortType{
	ContainerPortTypeTcp,
	ContainerPortTypeUdp,
}

type ContainerState string

const (
	ContainerStateRunning ContainerState = "RUNNING"
	ContainerStatePaused  ContainerState = "PAUSED"
	ContainerStateExited  ContainerState = "EXITED"
)

var AllContainerState = []ContainerState{
	ContainerStateRunning,
	ContainerStatePaused,
	ContainerStateExited,
}

// ForceStopVmResponse is returned by ForceStopVm on success.
type ForceStopVmResponse struct {
	Vm ForceStopVmVmVmMutations `json:"vm"`
}

// GetVm returns ForceStopVmResponse.Vm, and is useful for accessing the field via an interface.
func (v *ForceStopVmResponse) GetVm() ForceStopVmVmVmMutations { return v.Vm }

// ForceStopVmVmVmMutations includes the requested fields of the GraphQL type VmMutations.
type ForceStopVmVmVmMutations struct {
	// Force stop a virtual machine
	ForceStop bool `json:"forceStop"`
}

// GetForceStop returns ForceStopVmVmVmMutations.ForceStop, and is useful for accessing the field via an interface.
func (v *ForceStopVmVmVmMutations) GetForceStop() bool { return v.ForceStop }

// GetArrayArrayUnraidArray includes the requested fields of the GraphQL type UnraidArray.
type GetArrayArrayUnraidArray struct {
	Id string `json:"id"`
	// Current array state
	State ArrayState `json:"state"`
	// Parity disks in the current array
	Parities []GetArrayArrayUnraidArrayParitiesArrayDisk `json:"parities"`
	// Data disks in the current array
	Disks []GetArrayArrayUnraidArrayDisksArrayDisk `json:"disks"`
	// Caches in the current array
	Caches []GetArrayArrayUnraidArrayCachesArrayDisk `json:"caches"`
}

// GetId returns GetArrayArrayUnraidArray.Id, and is useful for accessing the field via an interface.
func (v *GetArrayArrayUnraidArray) GetId() string { return v.Id }

// GetState returns GetArrayArrayUnraidArray.State, and is useful for accessing the field via an interface.
func (v *GetArrayArrayUnraidArray) GetState() ArrayState { return v.State }

// GetParities returns GetArrayArrayUnraidArray.Parities, and is useful for accessing the field via an interface.
func (v *GetArrayArrayUnraidArray) GetParities() []GetArrayArrayUnraidArrayParitiesArrayDisk {
	return v.Parities
}

// GetDisks returns GetArrayArrayUnraidArray.Disks, and is useful for accessing the field via an interface.
func (v *GetArrayArrayUnraidArray) GetDisks() []GetArrayArrayUnraidArrayDisksArrayDisk {
	return v.Disks
}

// GetCaches returns GetArrayArrayUnraidArray.Caches, and is useful for accessing the field via an interface.
func (v *GetArrayArrayUnraidArray) GetCaches() []GetArrayArrayUnraidArrayCachesArrayDisk {
	return v.Caches
}

// GetArrayArrayUnraidArrayCachesArrayDisk includes the requested fields of the GraphQL type ArrayDisk.
type GetArrayArrayUnraidArrayCachesArrayDisk struct {
	Id     string           `json:"id"`
	Name   *string          `json:"name"`
	Device *string          `json:"device"`
	Status *ArrayDiskStatus `json:"status"`
	// (KB) Disk Size total
	Size *int64 `json:"size"`
	// (KB) Total Size of the FS (Not present on Parity type drive)
	FsSize *int64 `json:"fsSize"`
	// (KB) Free Size on the FS (Not present on Parity type drive)
	FsFree *int64 `json:"fsFree"`
	// Whether the disk is currently spinning
	IsSpinning *bool `json:"isSpinning"`
}

// GetId returns GetArrayArrayUnraidArrayCachesArrayDisk.Id, and is useful for accessing the field via an interface.
func (v *GetArrayArrayUnraidArrayCachesArrayDisk) GetId() string { return v.Id }

// GetName returns GetArrayArrayUnraidArrayCachesArrayDisk.Name, and is useful for accessing the field via an interface.
func (v *GetArrayArrayUnraidArrayCachesArrayDisk) GetName() *string { return v.Name }

// GetDevice returns GetArrayArrayUnraidArrayCachesArrayDisk.Device, and is useful for accessing the field via an interface.
func (v *GetArrayArrayUnraidArrayCachesArrayDisk) GetDevice() *string { return v.Device }

// GetStatus returns GetArrayArrayUnraidArrayCachesArrayDisk.Status, and is useful for accessing the field via an interface.
func (v *GetArrayArrayUnraidArrayCachesArrayDisk) GetStatus() *ArrayDiskStatus { return v.Status }

// GetSize returns GetArrayArrayUnraidArrayCachesArrayDisk.Size, and is useful for accessing the field via an interface.
func (v *GetArrayArrayUnraidArrayCachesArrayDisk) GetSize() *int64 { return v.Size }

// GetFsSize returns GetArrayArrayUnraidArrayCachesArrayDisk.FsSize, and is useful for accessing the field via an interface.
func (v *GetArrayArrayUnraidArrayCachesArrayDisk) GetFsSize() *int64 { return v.FsSize }

// GetFsFree returns GetArrayArrayUnraidArrayCachesArrayDisk.FsFree, and is useful for accessing the field via an interface.
func (v *GetArrayArrayUnraidArrayCachesArrayDisk) GetFsFree() *int64 { return v.FsFree }

// GetIsSpinning returns GetArrayArrayUnraidArrayCachesArrayDisk.IsSpinning, and is useful for accessing the field via an interface.
func (v *GetArrayArrayUnraidArrayCachesArrayDisk) GetIsSpinning() *bool { return v.IsSpinning }

// GetArrayArrayUnraidArrayDisksArrayDisk includes the requested fields of the GraphQL type ArrayDisk.
type GetArrayArrayUnraidArrayDisksArrayDisk struct {
	Id     string           `json:"id"`
	Name   *string          `json:"name"`
	Device *string          `json:"device"`
	Status *ArrayDiskStatus `json:"status"`
	// (KB) Disk Size total
	Size *int64 `json:"size"`
	// (KB) Total Size of the FS (Not present on Parity type drive)
	FsSize *int64 `json:"fsSize"`
	// (KB) Free Size on the FS (Not present on Parity type drive)
	FsFree *int64 `json:"fsFree"`
	// Whether the disk is currently spinning
	IsSpinning *bool `json:"isSpinning"`
}

// GetId returns GetArrayArrayUnraidArrayDisksArrayDisk.Id, and is useful for accessing the field via an interface.
func (v *GetArrayArrayUnraidArrayDisksArrayDisk) GetId() string { return v.Id }

// GetName returns GetArrayArrayUnraidArrayDisksArrayDisk.Name, and is useful for accessing the field via an interface.
func (v *GetArrayArrayUnraidArrayDisksArrayDisk) GetName() *string { return v.Name }

// GetDevice returns GetArrayArrayUnraidArrayDisksArrayDisk.Device, and is useful for accessing the field via an interface.
func (v *GetArrayArrayUnraidArrayDisksArrayDisk) GetDevice() *string { return v.Device }

// GetStatus returns GetArrayArrayUnraidArrayDisksArrayDisk.Status, and is useful for accessing the field via an interface.
func (v *GetArrayArrayUnraidArrayDisksArrayDisk) GetStatus() *ArrayDiskStatus { return v.Status }

// GetSize returns GetArrayArrayUnraidArrayDisksArrayDisk.Size, and is useful for accessing the field via an interface.
func (v *GetArrayArrayUnraidArrayDisksArrayDisk) GetSize() *int64 { return v.Size }

// GetFsSize returns GetArrayArrayUnraidArrayDisksArrayDisk.FsSize, and is useful for accessing the field via an interface.
func (v *GetArrayArrayUnraidArrayDisksArrayDisk) GetFsSize() *int64 { return v.FsSize }

// GetFsFree returns GetArrayArrayUnraidArrayDisksArrayDisk.FsFree, and is useful for accessing the field via an interface.
func (v *GetArrayArrayUnraidArrayDisksArrayDisk) GetFsFree() *int64 { return v.FsFree }

// GetIsSpinning returns GetArrayArrayUnraidArrayDisksArrayDisk.IsSpinning, and is useful for accessing the field via an interface.
func (v *GetArrayArrayUnraidArrayDisksArrayDisk) GetIsSpinning() *bool { return v.IsSpinning }

// GetArrayArrayUnraidArrayParitiesArrayDisk includes the requested fields of the GraphQL type ArrayDisk.
type GetArrayArrayUnraidArrayParitiesArrayDisk struct {
	Id     string           `json:"id"`
	Name   *string          `json:"name"`
	Device *string          `json:"device"`
	Status *ArrayDiskStatus `json:"status"`
	// (KB) Disk Size total
	Size *int64 `json:"size"`
	// Whether the disk is currently spinning
	IsSpinning *bool `json:"isSpinning"`
}

// GetId returns GetArrayArrayUnraidArrayParitiesArrayDisk.Id, and is useful for accessing the field via an interface.
func (v *GetArrayArrayUnraidArrayParitiesArrayDisk) GetId() string { return v.Id }

// GetName returns GetArrayArrayUnraidArrayParitiesArrayDisk.Name, and is useful for accessing the field via an interface.
func (v *GetArrayArrayUnraidArrayParitiesArrayDisk) GetName() *string { return v.Name }

// GetDevice returns GetArrayArrayUnraidArrayParitiesArrayDisk.Device, and is useful for accessing the field via an interface.
func (v *GetArrayArrayUnraidArrayParitiesArrayDisk) GetDevice() *string { return v.Device }

// GetStatus returns GetArrayArrayUnraidArrayParitiesArrayDisk.Status, and is useful for accessing the field via an interface.
func (v *GetArrayArrayUnraidArrayParitiesArrayDisk) GetStatus() *ArrayDiskStatus { return v.Status }

// GetSize returns GetArrayArrayUnraidArrayParitiesArrayDisk.Size, and is useful for accessing the field via an interface.
func (v *GetArrayArrayUnraidArrayParitiesArrayDisk) GetSize() *int64 { return v.Size }

// GetIsSpinning returns GetArrayArrayUnraidArrayParitiesArrayDisk.IsSpinning, and is useful for accessing the field via an interface.
func (v *GetArrayArrayUnraidArrayParitiesArrayDisk) GetIsSpinning() *bool { return v.IsSpinning }

// GetArrayResponse is returned by GetArray on success.
type GetArrayResponse struct {
	Array GetArrayArrayUnraidArray `json:"array"`
}

// GetArray returns GetArrayResponse.Array, and is useful for accessing the field via an interface.
func (v *GetArrayResponse) GetArray() GetArrayArrayUnraidArray { return v.Array }

// GetContainerLogsDocker includes the requested fields of the GraphQL type Docker.
type GetContainerLogsDocker struct {
	// Access container logs. Requires specifying a target container id through resolver arguments.
	Logs GetContainerLogsDockerLogsDockerContainerLogs `json:"logs"`
}

// GetLogs returns GetContainerLogsDocker.Logs, and is useful for accessing the field via an interface.
func (v *GetContainerLogsDocker) GetLogs() GetContainerLogsDockerLogsDockerContainerLogs {
	return v.Logs
}

// GetContainerLogsDockerLogsDockerContainerLogs includes the requested fields of the GraphQL type DockerContainerLogs.
type GetContainerLogsDockerLogsDockerContainerLogs struct {
	Lines []GetContainerLogsDockerLogsDockerContainerLogsLinesDockerContainerLogLine `json:"lines"`
}

// GetLines returns GetContainerLogsDockerLogsDockerContainerLogs.Lines, and is useful for accessing the field via an interface.
func (v *GetContainerLogsDockerLogsDockerContainerLogs) GetLines() []GetContainerLogsDockerLogsDockerContainerLogsLinesDockerContainerLogLine {
	return v.Lines
}

// GetContainerLogsDockerLogsDockerContainerLogsLinesDockerContainerLogLine includes the requested fields of the GraphQL type DockerContainerLogLine.
type GetContainerLogsDockerLogsDockerContainerLogsLinesDockerContainerLogLine struct {
	Timestamp string `json:"timestamp"`
	Message   string `json:"message"`
}

// GetTimestamp returns GetContainerLogsDockerLogsDockerContainerLogsLinesDockerContainerLogLine.Timestamp, and is useful for accessing the field via an interface.
func (v *GetContainerLogsDockerLogsDockerContainerLogsLinesDockerContainerLogLine) GetTimestamp() string {
	return v.Timestamp
}

// GetMessage returns GetContainerLogsDockerLogsDockerContainerLogsLinesDockerContainerLogLine.Message, and is useful for accessing the field via an interface.
func (v *GetContainerLogsDockerLogsDockerContainerLogsLinesDockerContainerLogLine) GetMessage() string {
	return v.Message
}

// GetContainerLogsResponse is returned by GetContainerLogs on success.
type GetContainerLogsResponse struct {
	Docker GetContainerLogsDocker `json:"docker"`
}

// GetDocker returns GetContainerLogsResponse.Docker, and is useful for accessing the field via an interface.
func (v *GetContainerLogsResponse) GetDocker() GetContainerLogsDocker { return v.Docker }

// GetDockerContainersDocker includes the requested fields of the GraphQL type Docker.
type GetDockerContainersDocker struct {
	Containers []GetDockerContainersDockerContainersDockerContainer `json:"containers"`
}

// GetContainers returns GetDockerContainersDocker.Containers, and is useful for accessing the field via an interface.
func (v *GetDockerContainersDocker) GetContainers() []GetDockerContainersDockerContainersDockerContainer {
	return v.Containers
}

// GetDockerContainersDockerContainersDockerContainer includes the requested fields of the GraphQL type DockerContainer.
type GetDockerContainersDockerContainersDockerContainer struct {
	Id     string                                                                 `json:"id"`
	Names  []string                                                               `json:"names"`
	Image  string                                                                 `json:"image"`
	State  ContainerState                                                         `json:"state"`
	Status string                                                                 `json:"status"`
	Ports  []GetDockerContainersDockerContainersDockerContainerPortsContainerPort `json:"ports"`
}

// GetId returns GetDockerContainersDockerContainersDockerContainer.Id, and is useful for accessing the field via an interface.
func (v *GetDockerContainersDockerContainersDockerContainer) GetId() string { return v.Id }

// GetNames returns GetDockerContainersDockerContainersDockerContainer.Names, and is useful for accessing the field via an interface.
func (v *GetDockerContainersDockerContainersDockerContainer) GetNames() []string { return v.Names }

// GetImage returns GetDockerContainersDockerContainersDockerContainer.Image, and is useful for accessing the field via an interface.
func (v *GetDockerContainersDockerContainersDockerContainer) GetImage() string { return v.Image }

// GetState returns GetDockerContainersDockerContainersDockerContainer.State, and is useful for accessing the field via an interface.
func (v *GetDockerContainersDockerContainersDockerContainer) GetState() ContainerState {
	return v.State
}

// GetStatus returns GetDockerContainersDockerContainersDockerContainer.Status, and is useful for accessing the field via an interface.
func (v *GetDockerContainersDockerContainersDockerContainer) GetStatus() string { return v.Status }

// GetPorts returns GetDockerContainersDockerContainersDockerContainer.Ports, and is useful for accessing the field via an interface.
func (v *GetDockerContainersDockerContainersDockerContainer) GetPorts() []GetDockerContainersDockerContainersDockerContainerPortsContainerPort {
	return v.Ports
}

// GetDockerContainersDockerContainersDockerContainerPortsContainerPort includes the requested fields of the GraphQL type ContainerPort.
type GetDockerContainersDockerContainersDockerContainerPortsContainerPort struct {
	Ip          *string           `json:"ip"`
	PrivatePort *int              `json:"privatePort"`
	PublicPort  *int              `json:"publicPort"`
	Type        ContainerPortType `json:"type"`
}

// GetIp returns GetDockerContainersDockerContainersDockerContainerPortsContainerPort.Ip, and is useful for accessing the field via an interface.
func (v *GetDockerContainersDockerContainersDockerContainerPortsContainerPort) GetIp() *string {
	return v.Ip
}

// GetPrivatePort returns GetDockerContainersDockerContainersDockerContainerPortsContainerPort.PrivatePort, and is useful for accessing the field via an interface.
func (v *GetDockerContainersDockerContainersDockerContainerPortsContainerPort) GetPrivatePort() *int {
	return v.PrivatePort
}

// GetPublicPort returns GetDockerContainersDockerContainersDockerContainerPortsContainerPort.PublicPort, and is useful for accessing the field via an interface.
func (v *GetDockerContainersDockerContainersDockerContainerPortsContainerPort) GetPublicPort() *int {
	return v.PublicPort
}

// GetType returns GetDockerContainersDockerContainersDockerContainerPortsContainerPort.Type, and is useful for accessing the field via an interface.
func (v *GetDockerContainersDockerContainersDockerContainerPortsContainerPort) GetType() ContainerPortType {
	return v.Type
}

// GetDockerContainersResponse is returned by GetDockerContainers on success.
type GetDockerContainersResponse struct {
	Docker GetDockerContainersDocker `json:"docker"`
}

// GetDocker returns GetDockerContainersResponse.Docker, and is useful for accessing the field via an interface.
func (v *GetDockerContainersResponse) GetDocker() GetDockerContainersDocker { return v.Docker }

// GetLogFileLogFileLogFileContent includes the requested fields of the GraphQL type LogFileContent.
type GetLogFileLogFileLogFileContent struct {
	// Path to the log file
	Path string `json:"path"`
	// Content of the log file
	Content string `json:"content"`
	// Total number of lines in the file
	TotalLines int `json:"totalLines"`
}

// GetPath returns GetLogFileLogFileLogFileContent.Path, and is useful for accessing the field via an interface.
func (v *GetLogFileLogFileLogFileContent) GetPath() string { return v.Path }

// GetContent returns GetLogFileLogFileLogFileContent.Content, and is useful for accessing the field via an interface.
func (v *GetLogFileLogFileLogFileContent) GetContent() string { return v.Content }

// GetTotalLines returns GetLogFileLogFileLogFileContent.TotalLines, and is useful for accessing the field via an interface.
func (v *GetLogFileLogFileLogFileContent) GetTotalLines() int { return v.TotalLines }

// GetLogFileResponse is returned by GetLogFile on success.
type GetLogFileResponse struct {
	LogFile GetLogFileLogFileLogFileContent `json:"logFile"`
}

// GetLogFile returns GetLogFileResponse.LogFile, and is useful for accessing the field via an interface.
func (v *GetLogFileResponse) GetLogFile() GetLogFileLogFileLogFileContent { return v.LogFile }

// GetLogFilesLogFilesLogFile includes the requested fields of the GraphQL type LogFile.
type GetLogFilesLogFilesLogFile struct {
	// Name of the log file
	Name string `json:"name"`
	// Full path to the log file
	Path string `json:"path"`
}

// GetName returns GetLogFilesLogFilesLogFile.Name, and is useful for accessing the field via an interface.
func (v *GetLogFilesLogFilesLogFile) GetName() string { return v.Name }

// GetPath returns GetLogFilesLogFilesLogFile.Path, and is useful for accessing the field via an interface.
func (v *GetLogFilesLogFilesLogFile) GetPath() string { return v.Path }

// GetLogFilesResponse is returned by GetLogFiles on success.
type GetLogFilesResponse struct {
	LogFiles []GetLogFilesLogFilesLogFile `json:"logFiles"`
}

// GetLogFiles returns GetLogFilesResponse.LogFiles, and is useful for accessing the field via an interface.
func (v *GetLogFilesResponse) GetLogFiles() []GetLogFilesLogFilesLogFile { return v.LogFiles }

// GetServerVersionInfo includes the requested fields of the GraphQL type Info.
type GetServerVersionInfo struct {
	// Software versions
	Versions GetServerVersionInfoVersions `json:"versions"`
}

// GetVersions returns GetServerVersionInfo.Versions, and is useful for accessing the field via an interface.
func (v *GetServerVersionInfo) GetVersions() GetServerVersionInfoVersions { return v.Versions }

// GetServerVersionInfoVersions includes the requested fields of the GraphQL type InfoVersions.
type GetServerVersionInfoVersions struct {
	// Core system versions
	Core GetServerVersionInfoVersionsCoreCoreVersions `json:"core"`
}

// GetCore returns GetServerVersionInfoVersions.Core, and is useful for accessing the field via an interface.
func (v *GetServerVersionInfoVersions) GetCore() GetServerVersionInfoVersionsCoreCoreVersions {
	return v.Core
}

// GetServerVersionInfoVersionsCoreCoreVersions includes the requested fields of the GraphQL type CoreVersions.
type GetServerVersionInfoVersionsCoreCoreVersions struct {
	// Unraid version
	Unraid *string `json:"unraid"`
	// Unraid API version
	Api *string `json:"api"`
}

// GetUnraid returns GetServerVersionInfoVersionsCoreCoreVersions.Unraid, and is useful for accessing the field via an interface.
func (v *GetServerVersionInfoVersionsCoreCoreVersions) GetUnraid() *string { return v.Unraid }

// GetApi returns GetServerVersionInfoVersionsCoreCoreVersions.Api, and is useful for accessing the field via an interface.
func (v *GetServerVersionInfoVersionsCoreCoreVersions) GetApi() *string { return v.Api }

// GetServerVersionResponse is returned by GetServerVersion on success.
type GetServerVersionResponse struct {
	Info GetServerVersionInfo `json:"info"`
}

// GetInfo returns GetServerVersionResponse.Info, and is useful for accessing the field via an interface.
func (v *GetServerVersionResponse) GetInfo() GetServerVersionInfo { return v.Info }

// GetVmsResponse is returned by GetVms on success.
type GetVmsResponse struct {
	// Get information about all VMs on the system
	Vms GetVmsVms `json:"vms"`
}

// GetVms returns GetVmsResponse.Vms, and is useful for accessing the field via an interface.
func (v *GetVmsResponse) GetVms() GetVmsVms { return v.Vms }

// GetVmsVms includes the requested fields of the GraphQL type Vms.
type GetVmsVms struct {
	Domains []GetVmsVmsDomainsVmDomain `json:"domains"`
}

// GetDomains returns GetVmsVms.Domains, and is useful for accessing the field via an interface.
func (v *GetVmsVms) GetDomains() []GetVmsVmsDomainsVmDomain { return v.Domains }

// GetVmsVmsDomainsVmDomain includes the requested fields of the GraphQL type VmDomain.
type GetVmsVmsDomainsVmDomain struct {
	// The unique identifier for the vm (uuid)
	Id string `json:"id"`
	// A friendly name for the vm
	Name *string `json:"name"`
	// Current domain vm state
	State VmState `json:"state"`
}

// GetId returns GetVmsVmsDomainsVmDomain.Id, and is useful for accessing the field via an interface.
func (v *GetVmsVmsDomainsVmDomain) GetId() string { return v.Id }

// GetName returns GetVmsVmsDomainsVmDomain.Name, and is useful for accessing the field via an interface.
func (v *GetVmsVmsDomainsVmDomain) GetName() *string { return v.Name }

// GetState returns GetVmsVmsDomainsVmDomain.State, and is useful for accessing the field via an interface.
func (v *GetVmsVmsDomainsVmDomain) GetState() VmState { return v.State }

// PauseDockerContainerDockerDockerMutations includes the requested fields of the GraphQL type DockerMutations.
type PauseDockerContainerDockerDockerMutations struct {
	// Pause (Suspend) a container
	Pause PauseDockerContainerDockerDockerMutationsPauseDockerContainer `json:"pause"`
}

// GetPause returns PauseDockerContainerDockerDockerMutations.Pause, and is useful for accessing the field via an interface.
func (v *PauseDockerContainerDockerDockerMutations) GetPause() PauseDockerContainerDockerDockerMutationsPauseDockerContainer {
	return v.Pause
}

// PauseDockerContainerDockerDockerMutationsPauseDockerContainer includes the requested fields of the GraphQL type DockerContainer.
type PauseDockerContainerDockerDockerMutationsPauseDockerContainer struct {
	Id     string         `json:"id"`
	Names  []string       `json:"names"`
	State  ContainerState `json:"state"`
	Status string         `json:"status"`
}

// GetId returns PauseDockerContainerDockerDockerMutationsPauseDockerContainer.Id, and is useful for accessing the field via an interface.
func (v *PauseDockerContainerDockerDockerMutationsPauseDockerContainer) GetId() string { return v.Id }

// GetNames returns PauseDockerContainerDockerDockerMutationsPauseDockerContainer.Names, and is useful for accessing the field via an interface.
func (v *PauseDockerContainerDockerDockerMutationsPauseDockerContainer) GetNames() []string {
	return v.Names
}

// GetState returns PauseDockerContainerDockerDockerMutationsPauseDockerContainer.State, and is useful for accessing the field via an interface.
func (v *PauseDockerContainerDockerDockerMutationsPauseDockerContainer) GetState() ContainerState {
	return v.State
}

// GetStatus returns PauseDockerContainerDockerDockerMutationsPauseDockerContainer.Status, and is useful for accessing the field via an interface.
func (v *PauseDockerContainerDockerDockerMutationsPauseDockerContainer) GetStatus() string {
	return v.Status
}

// PauseDockerContainerResponse is returned by PauseDockerContainer on success.
type PauseDockerContainerResponse struct {
	Docker PauseDockerContainerDockerDockerMutations `json:"docker"`
}

// GetDocker returns PauseDockerContainerResponse.Docker, and is useful for accessing the field via an interface.
func (v *PauseDockerContainerResponse) GetDocker() PauseDockerContainerDockerDockerMutations {
	return v.Docker
}

// PauseVmResponse is returned by PauseVm on success.
type PauseVmResponse struct {
	Vm PauseVmVmVmMutations `json:"vm"`
}

// GetVm returns PauseVmResponse.Vm, and is useful for accessing the field via an interface.
func (v *PauseVmResponse) GetVm() PauseVmVmVmMutations { return v.Vm }

// PauseVmVmVmMutations includes the requested fields of the GraphQL type VmMutations.
type PauseVmVmVmMutations struct {
	// Pause a virtual machine
	Pause bool `json:"pause"`
}

// GetPause returns PauseVmVmVmMutations.Pause, and is useful for accessing the field via an interface.
func (v *PauseVmVmVmMutations) GetPause() bool { return v.Pause }

// RebootVmResponse is returned by RebootVm on success.
type RebootVmResponse struct {
	Vm RebootVmVmVmMutations `json:"vm"`
}

// GetVm returns RebootVmResponse.Vm, and is useful for accessing the field via an interface.
func (v *RebootVmResponse) GetVm() RebootVmVmVmMutations { return v.Vm }

// RebootVmVmVmMutations includes the requested fields of the GraphQL type VmMutations.
type RebootVmVmVmMutations struct {
	// Reboot a virtual machine
	Reboot bool `json:"reboot"`
}

// GetReboot returns RebootVmVmVmMutations.Reboot, and is useful for accessing the field via an interface.
func (v *RebootVmVmVmMutations) GetReboot() bool { return v.Reboot }

// ResetVmResponse is returned by ResetVm on success.
type ResetVmResponse struct {
	Vm ResetVmVmVmMutations `json:"vm"`
}

// GetVm returns ResetVmResponse.Vm, and is useful for accessing the field via an interface.
func (v *ResetVmResponse) GetVm() ResetVmVmVmMutations { return v.Vm }

// ResetVmVmVmMutations includes the requested fields of the GraphQL type VmMutations.
type ResetVmVmVmMutations struct {
	// Reset a virtual machine
	Reset bool `json:"reset"`
}

// GetReset returns ResetVmVmVmMutations.Reset, and is useful for accessing the field via an interface.
func (v *ResetVmVmVmMutations) GetReset() bool { return v.Reset }

// ResumeVmResponse is returned by ResumeVm on success.
type ResumeVmResponse struct {
	Vm ResumeVmVmVmMutations `json:"vm"`
}

// GetVm returns ResumeVmResponse.Vm, and is useful for accessing the field via an interface.
func (v *ResumeVmResponse) GetVm() ResumeVmVmVmMutations { return v.Vm }

// ResumeVmVmVmMutations includes the requested fields of the GraphQL type VmMutations.
type ResumeVmVmVmMutations struct {
	// Resume a virtual machine
	Resume bool `json:"resume"`
}

// GetResume returns ResumeVmVmVmMutations.Resume, and is useful for accessing the field via an interface.
func (v *ResumeVmVmVmMutations) GetResume() bool { return v.Resume }

// SetArrayStateArrayArrayMutations includes the requested fields of the GraphQL type ArrayMutations.
type SetArrayStateArrayArrayMutations struct {
	// Set array state
	SetState SetArrayStateArrayArrayMutationsSetStateUnraidArray `json:"setState"`
}

// GetSetState returns SetArrayStateArrayArrayMutations.SetState, and is useful for accessing the field via an interface.
func (v *SetArrayStateArrayArrayMutations) GetSetState() SetArrayStateArrayArrayMutationsSetStateUnraidArray {
	return v.SetState
}

// SetArrayStateArrayArrayMutationsSetStateUnraidArray includes the requested fields of the GraphQL type UnraidArray.
type SetArrayStateArrayArrayMutationsSetStateUnraidArray struct {
	Id string `json:"id"`
	// Current array state
	State ArrayState `json:"state"`
}

// GetId returns SetArrayStateArrayArrayMutationsSetStateUnraidArray.Id, and is useful for accessing the field via an interface.
func (v *SetArrayStateArrayArrayMutationsSetStateUnraidArray) GetId() string { return v.Id }

// GetState returns SetArrayStateArrayArrayMutationsSetStateUnraidArray.State, and is useful for accessing the field via an interface.
func (v *SetArrayStateArrayArrayMutationsSetStateUnraidArray) GetState() ArrayState { return v.State }

// SetArrayStateResponse is returned by SetArrayState on success.
type SetArrayStateResponse struct {
	Array SetArrayStateArrayArrayMutations `json:"array"`
}

// GetArray returns SetArrayStateResponse.Array, and is useful for accessing the field via an interface.
func (v *SetArrayStateResponse) GetArray() SetArrayStateArrayArrayMutations { return v.Array }

// StartDockerContainerDockerDockerMutations includes the requested fields of the GraphQL type DockerMutations.
type StartDockerContainerDockerDockerMutations struct {
	// Start a container
	Start StartDockerContainerDockerDockerMutationsStartDockerContainer `json:"start"`
}

// GetStart returns StartDockerContainerDockerDockerMutations.Start, and is useful for accessing the field via an interface.
func (v *StartDockerContainerDockerDockerMutations) GetStart() StartDockerContainerDockerDockerMutationsStartDockerContainer {
	return v.Start
}

// StartDockerContainerDockerDockerMutationsStartDockerContainer includes the requested fields of the GraphQL type DockerContainer.
type StartDockerContainerDockerDockerMutationsStartDockerContainer struct {
	Id     string         `json:"id"`
	Names  []string       `json:"names"`
	State  ContainerState `json:"state"`
	Status string         `json:"status"`
}

// GetId returns StartDockerContainerDockerDockerMutationsStartDockerContainer.Id, and is useful for accessing the field via an interface.
func (v *StartDockerContainerDockerDockerMutationsStartDockerContainer) GetId() string { return v.Id }

// GetNames returns StartDockerContainerDockerDockerMutationsStartDockerContainer.Names, and is useful for accessing the field via an interface.
func (v *StartDockerContainerDockerDockerMutationsStartDockerContainer) GetNames() []string {
	return v.Names
}

// GetState returns StartDockerContainerDockerDockerMutationsStartDockerContainer.State, and is useful for accessing the field via an interface.
func (v *StartDockerContainerDockerDockerMutationsStartDockerContainer) GetState() ContainerState {
	return v.State
}

// GetStatus returns StartDockerContainerDockerDockerMutationsStartDockerContainer.Status, and is useful for accessing the field via an interface.
func (v *StartDockerContainerDockerDockerMutationsStartDockerContainer) GetStatus() string {
	return v.Status
}

// StartDockerContainerResponse is returned by StartDockerContainer on success.
type StartDockerContainerResponse struct {
	Docker StartDockerContainerDockerDockerMutations `json:"docker"`
}

// GetDocker returns StartDockerContainerResponse.Docker, and is useful for accessing the field via an interface.
func (v *StartDockerContainerResponse) GetDocker() StartDockerContainerDockerDockerMutations {
	return v.Docker
}

// StartVmResponse is returned by StartVm on success.
type StartVmResponse struct {
	Vm StartVmVmVmMutations `json:"vm"`
}

// GetVm returns StartVmResponse.Vm, and is useful for accessing the field via an interface.
func (v *StartVmResponse) GetVm() StartVmVmVmMutations { return v.Vm }

// StartVmVmVmMutations includes the requested fields of the GraphQL type VmMutations.
type StartVmVmVmMutations struct {
	// Start a virtual machine
	Start bool `json:"start"`
}

// GetStart returns StartVmVmVmMutations.Start, and is useful for accessing the field via an interface.
func (v *StartVmVmVmMutations) GetStart() bool { return v.Start }

// StopDockerContainerDockerDockerMutations includes the requested fields of the GraphQL type DockerMutations.
type StopDockerContainerDockerDockerMutations struct {
	// Stop a container
	Stop StopDockerContainerDockerDockerMutationsStopDockerContainer `json:"stop"`
}

// GetStop returns StopDockerContainerDockerDockerMutations.Stop, and is useful for accessing the field via an interface.
func (v *StopDockerContainerDockerDockerMutations) GetStop() StopDockerContainerDockerDockerMutationsStopDockerContainer {
	return v.Stop
}

// StopDockerContainerDockerDockerMutationsStopDockerContainer includes the requested fields of the GraphQL type DockerContainer.
type StopDockerContainerDockerDockerMutationsStopDockerContainer struct {
	Id     string         `json:"id"`
	Names  []string       `json:"names"`
	State  ContainerState `json:"state"`
	Status string         `json:"status"`
}

// GetId returns StopDockerContainerDockerDockerMutationsStopDockerContainer.Id, and is useful for accessing the field via an interface.
func (v *StopDockerContainerDockerDockerMutationsStopDockerContainer) GetId() string { return v.Id }

// GetNames returns StopDockerContainerDockerDockerMutationsStopDockerContainer.Names, and is useful for accessing the field via an interface.
func (v *StopDockerContainerDockerDockerMutationsStopDockerContainer) GetNames() []string {
	return v.Names
}

// GetState returns StopDockerContainerDockerDockerMutationsStopDockerContainer.State, and is useful for accessing the field via an interface.
func (v *StopDockerContainerDockerDockerMutationsStopDockerContainer) GetState() ContainerState {
	return v.State
}

// GetStatus returns StopDockerContainerDockerDockerMutationsStopDockerContainer.Status, and is useful for accessing the field via an interface.
func (v *StopDockerContainerDockerDockerMutationsStopDockerContainer) GetStatus() string {
	return v.Status
}

// StopDockerContainerResponse is returned by StopDockerContainer on success.
type StopDockerContainerResponse struct {
	Docker StopDockerContainerDockerDockerMutations `json:"docker"`
}

// GetDocker returns StopDockerContainerResponse.Docker, and is useful for accessing the field via an interface.
func (v *StopDockerContainerResponse) GetDocker() StopDockerContainerDockerDockerMutations {
	return v.Docker
}

// StopVmResponse is returned by StopVm on success.
type StopVmResponse struct {
	Vm StopVmVmVmMutations `json:"vm"`
}

// GetVm returns StopVmResponse.Vm, and is useful for accessing the field via an interface.
func (v *StopVmResponse) GetVm() StopVmVmVmMutations { return v.Vm }

// StopVmVmVmMutations includes the requested fields of the GraphQL type VmMutations.
type StopVmVmVmMutations struct {
	// Stop a virtual machine
	Stop bool `json:"stop"`
}

// GetStop returns StopVmVmVmMutations.Stop, and is useful for accessing the field via an interface.
func (v *StopVmVmVmMutations) GetStop() bool { return v.Stop }

// UnpauseDockerContainerDockerDockerMutations includes the requested fields of the GraphQL type DockerMutations.
type UnpauseDockerContainerDockerDockerMutations struct {
	// Unpause (Resume) a container
	Unpause UnpauseDockerContainerDockerDockerMutationsUnpauseDockerContainer `json:"unpause"`
}

// GetUnpause returns UnpauseDockerContainerDockerDockerMutations.Unpause, and is useful for accessing the field via an interface.
func (v *UnpauseDockerContainerDockerDockerMutations) GetUnpause() UnpauseDockerContainerDockerDockerMutationsUnpauseDockerContainer {
	return v.Unpause
}

// UnpauseDockerContainerDockerDockerMutationsUnpauseDockerContainer includes the requested fields of the GraphQL type DockerContainer.
type UnpauseDockerContainerDockerDockerMutationsUnpauseDockerContainer struct {
	Id     string         `json:"id"`
	Names  []string       `json:"names"`
	State  ContainerState `json:"state"`
	Status string         `json:"status"`
}

// GetId returns UnpauseDockerContainerDockerDockerMutationsUnpauseDockerContainer.Id, and is useful for accessing the field via an interface.
func (v *UnpauseDockerContainerDockerDockerMutationsUnpauseDockerContainer) GetId() string {
	return v.Id
}

// GetNames returns UnpauseDockerContainerDockerDockerMutationsUnpauseDockerContainer.Names, and is useful for accessing the field via an interface.
func (v *UnpauseDockerContainerDockerDockerMutationsUnpauseDockerContainer) GetNames() []string {
	return v.Names
}

// GetState returns UnpauseDockerContainerDockerDockerMutationsUnpauseDockerContainer.State, and is useful for accessing the field via an interface.
func (v *UnpauseDockerContainerDockerDockerMutationsUnpauseDockerContainer) GetState() ContainerState {
	return v.State
}

// GetStatus returns UnpauseDockerContainerDockerDockerMutationsUnpauseDockerContainer.Status, and is useful for accessing the field via an interface.
func (v *UnpauseDockerContainerDockerDockerMutationsUnpauseDockerContainer) GetStatus() string {
	return v.Status
}

// UnpauseDockerContainerResponse is returned by UnpauseDockerContainer on success.
type UnpauseDockerContainerResponse struct {
	Docker UnpauseDockerContainerDockerDockerMutations `json:"docker"`
}

// GetDocker returns UnpauseDockerContainerResponse.Docker, and is useful for accessing the field via an interface.
func (v *UnpauseDockerContainerResponse) GetDocker() UnpauseDockerContainerDockerDockerMutations {
	return v.Docker
}

// UpdateDockerContainerDockerDockerMutations includes the requested fields of the GraphQL type DockerMutations.
type UpdateDockerContainerDockerDockerMutations struct {
	// Update a container to the latest image
	UpdateContainer UpdateDockerContainerDockerDockerMutationsUpdateContainerDockerContainer `json:"updateContainer"`
}

// GetUpdateContainer returns UpdateDockerContainerDockerDockerMutations.UpdateContainer, and is useful for accessing the field via an interface.
func (v *UpdateDockerContainerDockerDockerMutations) GetUpdateContainer() UpdateDockerContainerDockerDockerMutationsUpdateContainerDockerContainer {
	return v.UpdateContainer
}

// UpdateDockerContainerDockerDockerMutationsUpdateContainerDockerContainer includes the requested fields of the GraphQL type DockerContainer.
type UpdateDockerContainerDockerDockerMutationsUpdateContainerDockerContainer struct {
	Id     string         `json:"id"`
	Names  []string       `json:"names"`
	State  ContainerState `json:"state"`
	Status string         `json:"status"`
}

// GetId returns UpdateDockerContainerDockerDockerMutationsUpdateContainerDockerContainer.Id, and is useful for accessing the field via an interface.
func (v *UpdateDockerContainerDockerDockerMutationsUpdateContainerDockerContainer) GetId() string {
	return v.Id
}

// GetNames returns UpdateDockerContainerDockerDockerMutationsUpdateContainerDockerContainer.Names, and is useful for accessing the field via an interface.
func (v *UpdateDockerContainerDockerDockerMutationsUpdateContainerDockerContainer) GetNames() []string {
	return v.Names
}

// GetState returns UpdateDockerContainerDockerDockerMutationsUpdateContainerDockerContainer.State, and is useful for accessing the field via an interface.
func (v *UpdateDockerContainerDockerDockerMutationsUpdateContainerDockerContainer) GetState() ContainerState {
	return v.State
}

// GetStatus returns UpdateDockerContainerDockerDockerMutationsUpdateContainerDockerContainer.Status, and is useful for accessing the field via an interface.
func (v *UpdateDockerContainerDockerDockerMutationsUpdateContainerDockerContainer) GetStatus() string {
	return v.Status
}

// UpdateDockerContainerResponse is returned by UpdateDockerContainer on success.
type UpdateDockerContainerResponse struct {
	Docker UpdateDockerContainerDockerDockerMutations `json:"docker"`
}

// GetDocker returns UpdateDockerContainerResponse.Docker, and is useful for accessing the field via an interface.
func (v *UpdateDockerContainerResponse) GetDocker() UpdateDockerContainerDockerDockerMutations {
	return v.Docker
}

// The state of a virtual machine
type VmState string

const (
	VmStateNostate     VmState = "NOSTATE"
	VmStateRunning     VmState = "RUNNING"
	VmStateIdle        VmState = "IDLE"
	VmStatePaused      VmState = "PAUSED"
	VmStateShutdown    VmState = "SHUTDOWN"
	VmStateShutoff     VmState = "SHUTOFF"
	VmStateCrashed     VmState = "CRASHED"
	VmStatePmsuspended VmState = "PMSUSPENDED"
)

var AllVmState = []VmState{
	VmStateNostate,
	VmStateRunning,
	VmStateIdle,
	VmStatePaused,
	VmStateShutdown,
	VmStateShutoff,
	VmStateCrashed,
	VmStatePmsuspended,
}

// __ForceStopVmInput is used internally by genqlient
type __ForceStopVmInput struct {
	Id string `json:"id"`
}

// GetId returns __ForceStopVmInput.Id, and is useful for accessing the field via an interface.
func (v *__ForceStopVmInput) GetId() string { return v.Id }

// __GetContainerLogsInput is used internally by genqlient
type __GetContainerLogsInput struct {
	Id   string `json:"id"`
	Tail *int   `json:"tail"`
}

// GetId returns __GetContainerLogsInput.Id, and is useful for accessing the field via an interface.
func (v *__GetContainerLogsInput) GetId() string { return v.Id }

// GetTail returns __GetContainerLogsInput.Tail, and is useful for accessing the field via an interface.
func (v *__GetContainerLogsInput) GetTail() *int { return v.Tail }

// __GetLogFileInput is used internally by genqlient
type __GetLogFileInput struct {
	Path  string `json:"path"`
	Lines *int   `json:"lines"`
}

// GetPath returns __GetLogFileInput.Path, and is useful for accessing the field via an interface.
func (v *__GetLogFileInput) GetPath() string { return v.Path }

// GetLines returns __GetLogFileInput.Lines, and is useful for accessing the field via an interface.
func (v *__GetLogFileInput) GetLines() *int { return v.Lines }

// __PauseDockerContainerInput is used internally by genqlient
type __PauseDockerContainerInput struct {
	Id string `json:"id"`
}

// GetId returns __PauseDockerContainerInput.Id, and is useful for accessing the field via an interface.
func (v *__PauseDockerContainerInput) GetId() string { return v.Id }

// __PauseVmInput is used internally by genqlient
type __PauseVmInput struct {
	Id string `json:"id"`
}

// GetId returns __PauseVmInput.Id, and is useful for accessing the field via an interface.
func (v *__PauseVmInput) GetId() string { return v.Id }

// __RebootVmInput is used internally by genqlient
type __RebootVmInput struct {
	Id string `json:"id"`
}

// GetId returns __RebootVmInput.Id, and is useful for accessing the field via an interface.
func (v *__RebootVmInput) GetId() string { return v.Id }

// __ResetVmInput is used internally by genqlient
type __ResetVmInput struct {
	Id string `json:"id"`
}

// GetId returns __ResetVmInput.Id, and is useful for accessing the field via an interface.
func (v *__ResetVmInput) GetId() string { return v.Id }

// __ResumeVmInput is used internally by genqlient
type __ResumeVmInput struct {
	Id string `json:"id"`
}

// GetId returns __ResumeVmInput.Id, and is useful for accessing the field via an interface.
func (v *__ResumeVmInput) GetId() string { return v.Id }

// __SetArrayStateInput is used internally by genqlient
type __SetArrayStateInput struct {
	DesiredState ArrayStateInputState `json:"desiredState"`
}

// GetDesiredState returns __SetArrayStateInput.DesiredState, and is useful for accessing the field via an interface.
func (v *__SetArrayStateInput) GetDesiredState() ArrayStateInputState { return v.DesiredState }

// __StartDockerContainerInput is used internally by genqlient
type __StartDockerContainerInput struct {
	Id string `json:"id"`
}

// GetId returns __StartDockerContainerInput.Id, and is useful for accessing the field via an interface.
func (v *__StartDockerContainerInput) GetId() string { return v.Id }

// __StartVmInput is used internally by genqlient
type __StartVmInput struct {
	Id string `json:"id"`
}

// GetId returns __StartVmInput.Id, and is useful for accessing the field via an interface.
func (v *__StartVmInput) GetId() string { return v.Id }

// __StopDockerContainerInput is used internally by genqlient
type __StopDockerContainerInput struct {
	Id string `json:"id"`
}

// GetId returns __StopDockerContainerInput.Id, and is useful for accessing the field via an interface.
func (v *__StopDockerContainerInput) GetId() string { return v.Id }

// __StopVmInput is used internally by genqlient
type __StopVmInput struct {
	Id string `json:"id"`
}

// GetId returns __StopVmInput.Id, and is useful for accessing the field via an interface.
func (v *__StopVmInput) GetId() string { return v.Id }

// __UnpauseDockerContainerInput is used internally by genqlient
type __UnpauseDockerContainerInput struct {
	Id string `json:"id"`
}

// GetId returns __UnpauseDockerContainerInput.Id, and is useful for accessing the field via an interface.
func (v *__UnpauseDockerContainerInput) GetId() string { return v.Id }

// __UpdateDockerContainerInput is used internally by genqlient
type __UpdateDockerContainerInput struct {
	Id string `json:"id"`
}

// GetId returns __UpdateDockerContainerInput.Id, and is useful for accessing the field via an interface.
func (v *__UpdateDockerContainerInput) GetId() string { return v.Id }

// The mutation executed by ForceStopVm.
const ForceStopVm_Operation = `
mutation ForceStopVm ($id: PrefixedID!) {
	vm {
		forceStop(id: $id)
	}
}
`

func ForceStopVm(
	ctx_ context.Context,
	client_ graphql.Client,
	id string,
) (data_ *ForceStopVmResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "ForceStopVm",
		Query:  ForceStopVm_Operation,
		Variables: &__ForceStopVmInput{
			Id: id,
		},
	}

	data_ = &ForceStopVmResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by GetArray.
const GetArray_Operation = `
query GetArray {
	array {
		id
		state
		parities {
			id
			name
			device
			status
			size
			isSpinning
		}
		disks {
			id
			name
			device
			status
			size
			fsSize
			fsFree
			isSpinning
		}
		caches {
			id
			name
			device
			status
			size
			fsSize
			fsFree
			isSpinning
		}
	}
}
`

func GetArray(
	ctx_ context.Context,
	client_ graphql.Client,
) (data_ *GetArrayResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "GetArray",
		Query:  GetArray_Operation,
	}

	data_ = &GetArrayResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by GetContainerLogs.
const GetContainerLogs_Operation = `
query GetContainerLogs ($id: PrefixedID!, $tail: Int) {
	docker {
		logs(id: $id, tail: $tail) {
			lines {
				timestamp
				message
			}
		}
	}
}
`

func GetContainerLogs(
	ctx_ context.Context,
	client_ graphql.Client,
	id string,
	tail *int,
) (data_ *GetContainerLogsResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "GetContainerLogs",
		Query:  GetContainerLogs_Operation,
		Variables: &__GetContainerLogsInput{
			Id:   id,
			Tail: tail,
		},
	}

	data_ = &GetContainerLogsResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by GetDockerContainers.
const GetDockerContainers_Operation = `
query GetDockerContainers {
	docker {
		containers {
			id
			names
			image
			state
			status
			ports {
				ip
				privatePort
				publicPort
				type
			}
		}
	}
}
`

func GetDockerContainers(
	ctx_ context.Context,
	client_ graphql.Client,
) (data_ *GetDockerContainersResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "GetDockerContainers",
		Query:  GetDockerContainers_Operation,
	}

	data_ = &GetDockerContainersResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by GetLogFile.
const GetLogFile_Operation = `
query GetLogFile ($path: String!, $lines: Int) {
	logFile(path: $path, lines: $lines) {
		path
		content
		totalLines
	}
}
`

func GetLogFile(
	ctx_ context.Context,
	client_ graphql.Client,
	path string,
	lines *int,
) (data_ *GetLogFileResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "GetLogFile",
		Query:  GetLogFile_Operation,
		Variables: &__GetLogFileInput{
			Path:  path,
			Lines: lines,
		},
	}

	data_ = &GetLogFileResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by GetLogFiles.
const GetLogFiles_Operation = `
query GetLogFiles {
	logFiles {
		name
		path
	}
}
`

func GetLogFiles(
	ctx_ context.Context,
	client_ graphql.Client,
) (data_ *GetLogFilesResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "GetLogFiles",
		Query:  GetLogFiles_Operation,
	}

	data_ = &GetLogFilesResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by GetServerVersion.
const GetServerVersion_Operation = `
query GetServerVersion {
	info {
		versions {
			core {
				unraid
				api
			}
		}
	}
}
`

func GetServerVersion(
	ctx_ context.Context,
	client_ graphql.Client,
) (data_ *GetServerVersionResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "GetServerVersion",
		Query:  GetServerVersion_Operation,
	}

	data_ = &GetServerVersionResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by GetVms.
const GetVms_Operation = `
query GetVms {
	vms {
		domains {
			id
			name
			state
		}
	}
}
`

func GetVms(
	ctx_ context.Context,
	client_ graphql.Client,
) (data_ *GetVmsResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "GetVms",
		Query:  GetVms_Operation,
	}

	data_ = &GetVmsResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The mutation executed by PauseDockerContainer.
const PauseDockerContainer_Operation = `
mutation PauseDockerContainer ($id: PrefixedID!) {
	docker {
		pause(id: $id) {
			id
			names
			state
			status
		}
	}
}
`

func PauseDockerContainer(
	ctx_ context.Context,
	client_ graphql.Client,
	id string,
) (data_ *PauseDockerContainerResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "PauseDockerContainer",
		Query:  PauseDockerContainer_Operation,
		Variables: &__PauseDockerContainerInput{
			Id: id,
		},
	}

	data_ = &PauseDockerContainerResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The mutation executed by PauseVm.
const PauseVm_Operation = `
mutation PauseVm ($id: PrefixedID!) {
	vm {
		pause(id: $id)
	}
}
`

func PauseVm(
	ctx_ context.Context,
	client_ graphql.Client,
	id string,
) (data_ *PauseVmResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "PauseVm",
		Query:  PauseVm_Operation,
		Variables: &__PauseVmInput{
			Id: id,
		},
	}

	data_ = &PauseVmResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The mutation executed by RebootVm.
const RebootVm_Operation = `
mutation RebootVm ($id: PrefixedID!) {
	vm {
		reboot(id: $id)
	}
}
`

func RebootVm(
	ctx_ context.Context,
	client_ graphql.Client,
	id string,
) (data_ *RebootVmResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "RebootVm",
		Query:  RebootVm_Operation,
		Variables: &__RebootVmInput{
			Id: id,
		},
	}

	data_ = &RebootVmResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The mutation executed by ResetVm.
const ResetVm_Operation = `
mutation ResetVm ($id: PrefixedID!) {
	vm {
		reset(id: $id)
	}
}
`

func ResetVm(
	ctx_ context.Context,
	client_ graphql.Client,
	id string,
) (data_ *ResetVmResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "ResetVm",
		Query:  ResetVm_Operation,
		Variables: &__ResetVmInput{
			Id: id,
		},
	}

	data_ = &ResetVmResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The mutation executed by ResumeVm.
const ResumeVm_Operation = `
mutation ResumeVm ($id: PrefixedID!) {
	vm {
		resume(id: $id)
	}
}
`

func ResumeVm(
	ctx_ context.Context,
	client_ graphql.Client,
	id string,
) (data_ *ResumeVmResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "ResumeVm",
		Query:  ResumeVm_Operation,
		Variables: &__ResumeVmInput{
			Id: id,
		},
	}

	data_ = &ResumeVmResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The mutation executed by SetArrayState.
const SetArrayState_Operation = `
mutation SetArrayState ($desiredState: ArrayStateInputState!) {
	array {
		setState(input: {desiredState:$desiredState}) {
			id
			state
		}
	}
}
`

func SetArrayState(
	ctx_ context.Context,
	client_ graphql.Client,
	desiredState ArrayStateInputState,
) (data_ *SetArrayStateResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "SetArrayState",
		Query:  SetArrayState_Operation,
		Variables: &__SetArrayStateInput{
			DesiredState: desiredState,
		},
	}

	data_ = &SetArrayStateResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The mutation executed by StartDockerContainer.
const StartDockerContainer_Operation = `
mutation StartDockerContainer ($id: PrefixedID!) {
	docker {
		start(id: $id) {
			id
			names
			state
			status
		}
	}
}
`

func StartDockerContainer(
	ctx_ context.Context,
	client_ graphql.Client,
	id string,
) (data_ *StartDockerContainerResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "StartDockerContainer",
		Query:  StartDockerContainer_Operation,
		Variables: &__StartDockerContainerInput{
			Id: id,
		},
	}

	data_ = &StartDockerContainerResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The mutation executed by StartVm.
const StartVm_Operation = `
mutation StartVm ($id: PrefixedID!) {
	vm {
		start(id: $id)
	}
}
`

func StartVm(
	ctx_ context.Context,
	client_ graphql.Client,
	id string,
) (data_ *StartVmResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "StartVm",
		Query:  StartVm_Operation,
		Variables: &__StartVmInput{
			Id: id,
		},
	}

	data_ = &StartVmResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The mutation executed by StopDockerContainer.
const StopDockerContainer_Operation = `
mutation StopDockerContainer ($id: PrefixedID!) {
	docker {
		stop(id: $id) {
			id
			names
			state
			status
		}
	}
}
`

func StopDockerContainer(
	ctx_ context.Context,
	client_ graphql.Client,
	id string,
) (data_ *StopDockerContainerResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "StopDockerContainer",
		Query:  StopDockerContainer_Operation,
		Variables: &__StopDockerContainerInput{
			Id: id,
		},
	}

	data_ = &StopDockerContainerResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The mutation executed by StopVm.
const StopVm_Operation = `
mutation StopVm ($id: PrefixedID!) {
	vm {
		stop(id: $id)
	}
}
`

func StopVm(
	ctx_ context.Context,
	client_ graphql.Client,
	id string,
) (data_ *StopVmResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "StopVm",
		Query:  StopVm_Operation,
		Variables: &__StopVmInput{
			Id: id,
		},
	}

	data_ = &StopVmResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The mutation executed by UnpauseDockerContainer.
const UnpauseDockerContainer_Operation = `
mutation UnpauseDockerContainer ($id: PrefixedID!) {
	docker {
		unpause(id: $id) {
			id
			names
			state
			status
		}
	}
}
`

func UnpauseDockerContainer(
	ctx_ context.Context,
	client_ graphql.Client,
	id string,
) (data_ *UnpauseDockerContainerResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "UnpauseDockerContainer",
		Query:  UnpauseDockerContainer_Operation,
		Variables: &__UnpauseDockerContainerInput{
			Id: id,
		},
	}

	data_ = &UnpauseDockerContainerResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The mutation executed by UpdateDockerContainer.
const UpdateDockerContainer_Operation = `
mutation UpdateDockerContainer ($id: PrefixedID!) {
	docker {
		updateContainer(id: $id) {
			id
			names
			state
			status
		}
	}
}
`

func UpdateDockerContainer(
	ctx_ context.Context,
	client_ graphql.Client,
	id string,
) (data_ *UpdateDockerContainerResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "UpdateDockerContainer",
		Query:  UpdateDockerContainer_Operation,
		Variables: &__UpdateDockerContainerInput{
			Id: id,
		},
	}

	data_ = &UpdateDockerContainerResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}
