// Code generated by "go run ./cmd/generate-capabilities". DO NOT EDIT.
package client

// SchemaCapabilities holds GraphQL fields detected via introspection.
// A nil map means the type was not found in the server's schema.
type SchemaCapabilities struct {
	// QueryFields maps top-level Query field names that exist on this server.
	QueryFields map[string]bool
	// DockerMutations maps DockerMutations field names. Nil if not supported.
	DockerMutations map[string]bool
	// VmMutations maps VmMutations field names. Nil if not supported.
	VmMutations map[string]bool
}

// introspectionQuery fetches the mutation type fields used by this CLI.
const introspectionQuery = `{
  dockerMutations: __type(name: "DockerMutations") { fields { name } }
  vmMutations: __type(name: "VmMutations") { fields { name } }
  schema: __schema { queryType { fields { name } } }
}`

type introspectFieldEntry struct {
	Name string `json:"name"`
}

type introspectTypeResult struct {
	Fields []introspectFieldEntry `json:"fields"`
}

type introspectResponse struct {
	Data struct {
		DockerMutations *introspectTypeResult `json:"dockerMutations"`
		VmMutations     *introspectTypeResult `json:"vmMutations"`
		Schema          struct {
			QueryType struct {
				Fields []introspectFieldEntry `json:"fields"`
			} `json:"queryType"`
		} `json:"schema"`
	} `json:"data"`
	Errors []struct {
		Message string `json:"message"`
	} `json:"errors"`
}

// parseCapabilities converts an introspection response to SchemaCapabilities.
func parseCapabilities(r introspectResponse) *SchemaCapabilities {
	return &SchemaCapabilities{
		QueryFields:     fieldsToSet(r.Data.Schema.QueryType.Fields),
		DockerMutations: typeToSet(r.Data.DockerMutations),
		VmMutations:     typeToSet(r.Data.VmMutations),
	}
}
